name: DonateExecute
version: 1
api: 5.0.0
main: Taskov1ch\DonateExecute\DonateExecute
author: Taskov1ch
description: Donate = Execute command :D

permissions:
  donate_execute.allow_disallow_donates:
    default: op
  donate_execute.fake_donate:
    default: op