# Your token
# You can spin up a local web server via the get_token.py script to get your token.
token: "My very super-duper secret token from the DonationAlerts"

# Default language
default_language: en_US

# Players on whom donations will be valid (lowercase)
allowed_players:
  - taskov1ch
  - tester

# Delay between donations (in seconds)
delay: 10

# Allowed currencies
allowed_currencies:
  - RUB
  - USD
  - EUR
  - BRL
  - TRY
  - PLN

# Will be used in pricelist.yml if {sender} or {message} are empty.
default_sender: "Anonymous"
default_message: "..."